mutation addArticle {
  addArticle {
    id
    title
    shareDesc
    shareTitle
    content
    url
    createAt
    updateAt
    author {
      id
      avator
      name
      desc
      tag {
        text
      }
    }
  }
}
