mutation addArticle {
  addArticle {
    id
    title
    shareDesc
    shareTitle
    mainPic {
      url
    }
    thumbnail {
      url
    }
    content
    url
    createAt
    updateAt
    author {
      id
      avator
      name
      desc
      tag {
        text
      }
    }
  }
}
