/* eslint-disable */
export const STORE_HOMEPAGE_DATA = 'STORE_HOMEPAGE_DATA'
export const UPDATE_HOMEPAGE_DATA = 'UPDATE_HOMEPAGE_DATA'
export const SAVE_HOMEPAGE_DATA = 'SAVE_HOMEPAGE_DATA'

export const UPDATE_AUTHOR = 'UPDATE_AUTHOR'
export const STORE_AUTHOR = 'STORE_AUTHOR'
