/* eslint-disable */
export const STORE_HOMEPAGE_DATA = 'STORE_HOMEPAGE_DATA'
export const UPDATE_HOMEPAGE_DATA = 'UPDATE_HOMEPAGE_DATA'
export const SAVE_HOMEPAGE_DATA = 'SAVE_HOMEPAGE_DATA'

export const UPDATE_AUTHOR = 'UPDATE_AUTHOR'
export const STORE_AUTHOR = 'STORE_AUTHOR'
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR'

export const STORE_ARTICLELIST = 'STORE_ARTICLELIST'
export const STORE_ARTICLE = 'STORE_ARTICLE'
export const NEW_ARTICLE = 'NEW_ARTICLE'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'

export const FETCH = 'FETCH'

// 微信小程序首页数据
export const STORE_MINIHOMEPAGE_DATA = 'STORE_MINIHOMEPAGE_DATA'
export const UPDATE_MINIHOMEPAGE_DATA = 'UPDATE_MINIHOMEPAGE_DATA'
export const SAVE_MINIHOMEPAGE_DATA = 'SAVE_MINIHOMEPAGE_DATA'
export const FETCH_MINIHOMEPAGE = 'FETCH_MINIHOMEPAGE'

// 存储品牌列表
export const STORE_BRANDS = 'STORE_BRANDS'
